apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  custom.server: |
    consul:53 {
      errors
      cache 30
      forward . 10.0.135.245 # Change this IP address with your DNS proxy's external IP address
      reload
    }
