global:
  imageConsulDataplane: hashicorppreview/consul-dataplane:1.6.0-dev
  image: docker.mirror.hashicorp.services/hashicorppreview/consul-enterprise:1.20-dev
  
  adminPartitions:
    enabled: true
  enableConsulNamespaces: true
  enterpriseLicense:
    secretName: license
    secretKey: key  

  gossipEncryption:
    autoGenerate: true
  tls:
    enabled: true
    httpsOnly: false
    verify: false
    enableAutoEncrypt: true  
  acls:
    manageSystemACLs: true
    createReplicationToken: true
  connectInject:
  enabled: true
server:
  replicas: 1
  exposeGossipAndRPCPorts: true
ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
syncCatalog:
  enabled: true
  toConsul: true
  toK8S: false
  addK8SNamespaceSuffix: false
  ingress:
    enabled: true
    loadBalancerIPs: true    
dns:
  enabled: true
  proxy:
    enabled: true 
    replicas: 2
    type: LoadBalancer
meshGateway:
  enabled: true
